name: Test

on: [workflow_dispatch]
#  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  create-runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - id: create-runner
        uses: traversals-analytics-and-intelligence/gce-github-runner@main
        with:
          token: ${{ secrets.GIT_PERSONAL_ACCESS_TOKEN }}
          project_id: ${{ secrets.GCP_GITHUB_ACTIONS_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_GITHUB_ACTIONS_SA_KEY }}
          image_project: ubuntu-os-cloud
          image_family: ubuntu-2004-lts

  test:
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
      - run: echo "This runs on the GCE runner VM"
      - uses: traversals-analytics-and-intelligence/gce-github-runner@main
        with:
          command: stop
        if: always()
